### PR TITLE
Allow builders on self methods

### LINKED ISSUE #45: Use annotations to specify eligible methods for builder creation.
Proposal is that constructors should be annotated rather than using the `new/*'_new` convention.

```rust
#[buildstructor::buildstructor]
impl MyStruct {

    #[builder]
    fn new(a: usize, b: usize) -> MyStruct {
        Self { sum: a + b }
    }
}
```

This could be a really powerful tool for API creation as we could allow methods that take self to have builders.
e.g. 
```rust
connection.get().header("a", "b").body("").send()
```

### PR DESCRIPTION
**Pull request by BrynCooke**
Major refactor to expand the scope of buildstructor.

This is a **breaking** change although old code will compile with a deprecation notice.

To use buildstructor you now have to annotate the impl and the methods you want a builder for:

Annotate the impl with: `#[buildstructor::buildstructor]`
Annotate the method with: `#[builder]`

```rust
#[buildstructor::buildstructor]
impl Foo {
    #[builder]
    fn new(simple: String) -> Foo {
        Self { simple }
    }
}
```

You can configure your builder using the `#[builder]` annotation, which has the following attributes:
* `entry` => The entry point for your builder. If not specified then the pre-existing rules around `new/*_new` are used. If your method a compile error is generated to prompt to specify `entry` manually..
* `exit` => The terminal method for the generated builder. Defaults to `builder` for methods that do not have a receiver and `call` for those that do..

In addition, you can now specify builders on methods that take self:

```rust
#[derive(Default)]
pub struct Client;

#[buildstructor::buildstructor]
impl Client {
    #[builder(entry = "message", exit = "send")]
    fn call_with_no_return(self, _simple: String) {}

    #[builder(entry = "message_ref", exit = "send")]
    fn call_with_no_return_ref(&self, _simple: String) {}

    #[builder(entry = "message_ref_mut", exit = "send")]
    fn call_with_no_return_ref_mut(&mut self, _simple: String) {}
    
}

fn main() {
    Client::default().message().simple("3".to_string()).send();

    let client = Client::default();
    client.message_ref().simple("3".to_string()).send();

    let mut client = Client::default();
    client.message_ref_mut().simple("3".to_string()).send();
}
```

Note, if method parameters begin with `_` then this is stripped for the builder method names.

Finally you can bring back the old behaviour around automatic builders by using:

```
#[buildstructor(default_builders = true)]
```

### CODE REVIEW

**Comment by garypen** [comment]
I liked the old "auto-find" feature. Could there be a solution which supports both (implicit and explicit) approaches? Extra points for being backwards-compatible. I could imagine something like this
```
#[buildstructor::buildstructor(explicit = true)]
impl Foo {
    #[builder]
    fn new(simple: String) -> Foo {
        Self { simple }
    }
}

#[buildstructor::buildstructor(explicit = false)]
impl Foo {
    fn new(simple: String) -> Foo {
        Self { simple }
    }
}
```
These would generate the same code and if `explicit = false` is the default, then it would also be backwards compatible...

**Comment by BrynCooke** [comment]
> I liked the old "auto-find" feature. 

Yeah, I also likes this as it forced convention on naming, The rules still sort of exist, but for methods that take a receiver they are not great at the moment.

I think a combination of your suggestion and firming up the rules for conventions would be enough to get this over the line.
Suggestion for the defaults:

* `new` => `builder` -> `build`
* `*_new` => `*_builder` -> `build`
* ~~`call_foo` => `foo` -> `call`~~ (This was a bad idea)

**Comment by BrynCooke** [comment]
Updated the PR, although took out defaulting around methods with a receiver.

You can use the following to bring back the behaviour around automatically creating builders for constructors.
```
#[buildstructor(default_builders = true)]
```

Still not sure if this should be enabled by default.

Docs still need updating.

**Comment by BrynCooke** [comment]
So after some deliberation I removed the default_builders config option. When writing the documentation there were too many permutations to cover and it was getting confusing.

Another advantage of annotating methods explicitly is that it's very clear when looking at the code that there is a generated builder.

I did like the configuration by convention way that things operated before, but it didn't have enough advantages in the face of allowing users to explicitly set `entry` and `exit` methods.

**Pull request merged**
